import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

import { SessionProvider } from "next-auth/react"
import { AuthProvider } from "@/utils/ProvidersAuth";
import ProgresBarProvider from "@/utils/ProgresBarProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, params: { session, ...params}, }) {
  return (
    
      <html lang="en">
        <body className={inter.className}>
        <AuthProvider>
          <ProgresBarProvider>
              <Header />
                <div className=' pt-24'>
                  {children}
                </div>
              <Footer />
          </ProgresBarProvider>
        </AuthProvider>
        </body>
      </html>
  );
}
